Repository Siteimprove/alfa-integrations, pull requests merged in 2024-08, with the labels that each got.

#61 Add audit wrapper to `alfa-test-utils`
  .changeset/spotty-toes-sniff.md
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/package.json
  packages/alfa-test-utils/src/audit/audit.ts
  packages/alfa-test-utils/src/audit/index.ts
  packages/alfa-test-utils/src/audit/outcomes.ts
  packages/alfa-test-utils/src/audit/rules.ts
  packages/alfa-test-utils/src/index.ts
  packages/alfa-test-utils/src/tsconfig.json
  packages/alfa-test-utils/test/audit/audit.spec.tsx
  packages/alfa-test-utils/test/audit/fixtures.spec.tsx
  packages/alfa-test-utils/test/audit/outcomes.spec.tsx
  packages/alfa-test-utils/test/audit/rules.spec.tsx
  packages/alfa-test-utils/test/fixtures.ts
  packages/alfa-test-utils/test/report/sip.spec.tsx
  packages/alfa-test-utils/test/tsconfig.json
  yarn.lock
Labels: minor

#63 Remove pre-built rule sets
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/src/audit/rules.ts
Labels: internal

#62 `alfa-test-utils`: extract and send metadata to the Siteimprove Intelligence Platform
  config/validate-structure.json
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/README.md
  packages/alfa-test-utils/package.json
  packages/alfa-test-utils/src/audit/audit.ts
  packages/alfa-test-utils/src/audit/index.ts
  packages/alfa-test-utils/src/audit/performance.ts
  packages/alfa-test-utils/src/report/git.ts
  packages/alfa-test-utils/src/report/sip.ts
  packages/alfa-test-utils/src/tsconfig.json
  packages/alfa-test-utils/test/audit/audit.spec.tsx
  packages/alfa-test-utils/test/report/git.spec.ts
  packages/alfa-test-utils/test/report/sip.spec.tsx
  packages/alfa-test-utils/test/tsconfig.json
  yarn.lock
Labels: minor

#65 Update dependency graphs
  packages/alfa-assert/docs/dependency-graph.dot
  packages/alfa-assert/docs/dependency-graph.svg
  packages/alfa-cli/docs/dependency-graph.dot
  packages/alfa-cli/docs/dependency-graph.svg
  packages/alfa-command/docs/dependency-graph.dot
  packages/alfa-command/docs/dependency-graph.svg
  packages/alfa-scraper/docs/dependency-graph.dot
  packages/alfa-scraper/docs/dependency-graph.svg
  packages/alfa-test-utils/docs/dependency-graph.dot
  packages/alfa-test-utils/docs/dependency-graph.svg
  packages/alfa-webdriver/docs/dependency-graph.dot
  packages/alfa-webdriver/docs/dependency-graph.svg
Labels: documentation, internal

#67 Add console output
  .changeset/shiny-tomatoes-remember.md
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/src/report/get-rule-title.ts
  packages/alfa-test-utils/src/report/logging.ts
  packages/alfa-test-utils/src/tsconfig.json
Labels: patch

#64 Console logging
  .changeset/shiny-tomatoes-remember.md
  config/validate-structure.json
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/package.json
  packages/alfa-test-utils/src/report/get-rule-title.ts
  packages/alfa-test-utils/src/report/index.ts
  packages/alfa-test-utils/src/report/logging.ts
  packages/alfa-test-utils/src/tsconfig.json
  yarn.lock
Labels: patch

#66 Add documentation for the Accessibility Code Checker
  .changeset/fair-zoos-join.md
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/README.md
  packages/alfa-test-utils/docs/usage/README.md
  packages/alfa-test-utils/docs/usage/auditing/advanced.md
  packages/alfa-test-utils/docs/usage/auditing/basic.md
  packages/alfa-test-utils/docs/usage/auditing/configuration.md
  packages/alfa-test-utils/docs/usage/gatekeeping/manual.md
  packages/alfa-test-utils/docs/usage/github-registry.md
  packages/alfa-test-utils/docs/usage/reporting/advanced.md
  packages/alfa-test-utils/docs/usage/reporting/basic.md
  packages/alfa-test-utils/docs/usage/reporting/configuration.md
  packages/alfa-test-utils/docs/usage/scraping/advanced.md
  packages/alfa-test-utils/docs/usage/scraping/integrated.md
  packages/alfa-test-utils/package.json
  packages/alfa-test-utils/src/audit/rules.ts
  packages/alfa-test-utils/src/report/git.ts
  packages/alfa-test-utils/src/report/index.ts
Labels: documentation, patch

#72 Ward PR command steps
  .github/workflows/pr-command.yml
Labels: actions
