Repository Siteimprove/alfa-integrations, pull requests merged in 2025-01, with the labels that each got.

#123 Remove private GitHub package registry usage
  .yarnrc.yml
  README.md
  package.json
  renovate.json
  yarn.lock
Labels: npm, dependencies, internal

#120 Handling upload errors in logging
  .changeset/mighty-goats-sell.md
  .changeset/strange-numbers-poke.md
  .changeset/tidy-buses-approve.md
  docs/review/api/alfa-test-utils.api.md
  packages/alfa-test-utils/package.json
  packages/alfa-test-utils/src/report/logging.ts
  packages/alfa-test-utils/src/report/sip.ts
  packages/alfa-test-utils/test/report/logging.spec.tsx
  packages/alfa-test-utils/test/report/sip.spec.tsx
  yarn.lock
Labels: minor

#124 Update Cypress and Puppeteer
  .changeset/chilled-bugs-rhyme.md
  .changeset/fifty-mails-grow.md
  packages/alfa-cypress/package.json
  packages/alfa-cypress/test/cypress.spec.ts
  packages/alfa-puppeteer/package.json
  packages/alfa-scraper/package.json
  packages/alfa-scraper/test/scraper.spec.ts
  yarn.lock
Labels: dependencies

#125 Update Changesets
  package.json
  packages/alfa-formatter-earl/package.json
  yarn.lock
Labels: internal
